### ISSUE TITLE
Question about fun ideas

### ISSUE THREAD

**Issue by piranna** [andrewchambers/cc#5]
> Compile toolchain to javascript using Gopherjs, cross compile using javascript.

This means to have a C compiler in Javascript? And being able to compile a C source code file from a Node.js executable? This would be awesome for [NodeOS](https://github.com/NodeOS/NodeOS)! :-D

**Comment by andrewchambers** [comment]
Yes, but there is still a long way to go before this compiler can handle complicated programs.

Currently this can be done using emscripten already with some of the other existing C compilers if you want results right away :). I would start by trying to compile http://bellard.org/tcc/ with https://github.com/kripken/emscripten.
